---

- name: install apache tomcat   
  yum:
    name: tomcat
    state: latest

- name: enable tomcat
  service:
    name: tomcat
    enabled: yes

- name: create ansible tomcat directory
  file:
    path: "{{tomcat_root_directory}}"
    state: directory

- name: copy static index.html to tomcat webapps/ansible/index.html
  template:
    src: index.html.j2
    dest: "{{tomcat_root_directory}}/index.html"
    mode: 0644

- name: restarting tomcat
  service:
    name: tomcat
    state: restarted
